### ISSUE TITLE
Erro de conexão com o BD

### ISSUE THREAD

**Issue by lucaszgoda** [fernandoacosta/Etiquetas-WooCommerce-Correios#2]
Olá, estou recebendo o seguinte erro quando abre a nova guia:

Table 'adventur_wp.wp_posts' doesn't exist

Estou tentando resolver aqui, se conseguir resolver posto uma solução e se tiver uma solução para isso por favor informar ;)

**Comment by fernandoacosta** [comment]
Olá, essa nova versão estava com problemas mesmo.

Favor baixar novamente: https://github.com/fernandoacosta/Etiquetas-WooCommerce-Correios

**Comment by lucaszgoda** [comment]
VALEU @fernandoacosta ! Isso vai reduzir muito o meu tempo de trabalho na minha loja virtual que estou fazendo. Por mais pessoas como você que compartilham soluções e não problemas!

**Comment by lucaszgoda** [comment]
Baixei e instalei novamente mas continua com o erro. Vou tentar baixar uma versão antiga

**Comment by lucaszgoda** [comment]
Já vi aqui o log de alterações e apliquei elas.
Pena que o remetente não deu certo, vou ver alguma forma de aplicar o meu endereço direto no PHP mesmo.
 
Usando o mesmo estilo do site dos correios que permite que remetente e destinatario fiquem do mesmo lado. ai fica mais pratico de imprimir e cortar ;)
Ficando legal eu te mando aqui
